endpoints:
  - name: chat
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-35-turbo
      config:
        openai_api_type: "azure"
        openai_api_key: "2d704bd3cf9442e4b1096f67f422db55"
        openai_deployment_name: "gpt-4"
        openai_api_base: "https://arwinopenai.openai.azure.com/"
        openai_api_version: "2023-07-01-preview"

  - name: completions
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-35-turbo
      config:
        openai_api_type: "azure"
        openai_api_key: "2d704bd3cf9442e4b1096f67f422db55"
        openai_deployment_name: "gpt-4"
        openai_api_base: "https://arwinopenai.openai.azure.com/"
        openai_api_version: "2023-07-01-preview"

  - name: embeddings
    endpoint_type: llm/v1/embeddings
    model:
      provider: openai
      name: text-embedding-ada-002
      config:
        openai_api_type: "azure"
        openai_api_key: "2d704bd3cf9442e4b1096f67f422db55"
        openai_deployment_name: "gpt-4"
        openai_api_base: "https://arwinopenai.openai.azure.com/"
        openai_api_version: "2023-07-01-preview"